'use strict';
// 자동 생성: 도구/에셋변환/PNG넣기.py — 손으로 다듬은 PNG를 그대로 옮긴 것. 고칠 때는 PNG를 고치고 다시 만든다.
// hd: 도트 1칸 = 화면 1px, raw: 자동 도트 규칙을 적용하지 않음 (사람이 다듬은 픽셀 그대로)
M('sunSprite', '햇살 정령', 'swarm', {"a": "#361812", "b": "#f68412", "d": "#fcba30", "f": "#f8ecd0"}, [
  "........a.....",
  ".....a.aba....",
  "....abaabba...",
  "...abdbbbdba..",
  "..adddddddba..",
  ".addfffffddba.",
  ".adfffffffdba.",
  "abdfaffaffdbba",
  "abdfaffaffdba.",
  ".adfffffffdba.",
  ".addfffffddba.",
  "..adddddddba..",
  "...adbdbaba...",
  "....abaa.a....",
  ".....a........"
], {"hd": false, "raw": true, "foot": 1, "fly": 10, "anim": {"kind": "hop", "top": 3}});
M('scorpion', '전갈', 'charger', {"a": "#361812", "b": "#fcc02a", "d": "#d86036", "f": "#fceaba", "g": "#a4442a", "h": "#ea7a40", "i": "#f6d8a2"}, [
  "............aaaa.....",
  "..........aabbddaa...",
  ".........abffbbddda..",
  ".........abffbbgddda.",
  "..........abbbaaddda.",
  "...........abbaagddda",
  "............aa..ahdda",
  "................addda",
  "...............ahhgga",
  "......aa..aa.aahhhda.",
  ".....aidaaidahddggga.",
  "..aaaaiiiiidghddgga..",
  ".ahhdaiaiaiddggggaaa.",
  "ahdddafaiaigaagagddaa",
  "ahdadaiiiiddddaddddda",
  "adaadaaaaaddddaddgada",
  ".aada....aadddaada.aa",
  "...a....addddaa.aa...",
  ".........aaaaa......."
], {"hd": false, "raw": true, "anim": {"kind": "scuttle", "foot": 16, "band": 4}});
M('sandSnake', '모래 뱀', 'ranged', {"a": "#361812", "b": "#f6d8a2", "d": "#fcba36", "f": "#1a8e8e", "g": "#d86036", "h": "#fce6b4", "i": "#a4442a", "j": "#c89868"}, [
  "......aa.......",
  ".....abda......",
  "....aaddaaaa...",
  "...adaddadda...",
  "...addddddda...",
  "..aaadddddaaa..",
  ".aafdgggdddda..",
  ".affgggggddda..",
  "ahggbabggdaa...",
  "ahhhhabbgiga...",
  ".ahhhhhbbiia...",
  ".ahhhhhhhiia...",
  ".aiaaajbbia....",
  "aga.ajjbbia....",
  ".aa.ahhbga.aa..",
  "...abhhgiaagba.",
  "...ahhhggabigga",
  "...ahhhggaaagga",
  "...ahhhggggggba",
  "...abbbbgggbgba",
  "....aabbbbgjja.",
  ".....aaaaaaaaa."
], {"hd": false, "raw": true, "anim": {"kind": "hop", "top": 5}});
M('clayGuard', '흙 병사', 'tank', {"a": "#361812", "b": "#cc5a36", "d": "#a84e30", "f": "#f8ecc8", "g": "#fcc660", "h": "#c88838", "i": "#30ccc0", "j": "#1a8e8e", "k": "#7a4a2c", "l": "#f0c084", "m": "#f6deae"}, [
  ".............aa.........",
  "............abba........",
  "..........aabbbdaa......",
  "..a......abbbbdaffa.....",
  ".aga.....abbbdffffa.....",
  ".aga.....abbddffffa.....",
  ".agga...aggggbdffaba....",
  "afgga..aggggbbghabbba...",
  "aggghaaggfggbbdgdbbba...",
  "agija.aggfgggbbdhhaa....",
  ".aija.agggggggghhha.....",
  ".agha.agggggggghhha.....",
  "..aga.ahhhhhhhhhhha.....",
  "..aka.alallallaaaaaaa...",
  "..aka.alallallaammmmmaa.",
  "...akaalllllaaamdddddma.",
  "...akaahhhhhaamdddgdddma",
  "..allklgggggaamddgggddma",
  "..allklggiigaamdgggggdma",
  "...aakaggijgaamgggfgggma",
  "....akagggggaamdgggggdma",
  "....akahhhhhaamddgggddma",
  "....akabbbbbbamdddgdddma",
  ".....aabbdaaa.amdddddma.",
  "......abbda...aammmmmaa.",
  ".....ammhha.....aaaaa...",
  ".....aaaaaa............."
], {"hd": false, "raw": true, "anim": {"kind": "heavy", "foot": 23, "head": 12, "arm": false}});
M('sunGolem', '태양 석상 골렘', 'boss', {"a": "#361812", "b": "#fcba3c", "d": "#c07a30", "f": "#f6d29c", "g": "#fae4b4", "h": "#5e4232", "i": "#c65a36", "j": "#c69666", "k": "#846042", "l": "#30ccc0", "m": "#1a8e8e"}, [
  ".................aaaa.................",
  "................aaabda................",
  "................abbbda...aa...........",
  "...........aa...abbbba..afba..........",
  "..........afba..abbbba..agba..........",
  ".........afbbdaaabbbbhaabbbda.........",
  ".........abbbbdaabbbbiabbbbda.........",
  ".......aa.abbbddhibbbibbbbda.aa.......",
  "......afbaadbbdfffdddhbbbda.afba......",
  "......afbbhabdffffjddbbbdiaabbba......",
  "......abbbbdafffffffdbbbdabbbbba......",
  "......abbbbaffffffffjdbbabbbbbda......",
  ".......abbaffffffffffjbddibbbda.......",
  "........abaffffffffffjbddibbda........",
  "......aaaahfaakffkaajkbddiddaaaaa.....",
  "....aaffjjafhlhffhlafkbddiaaaffjja....",
  "....affffjafhmhffhmmfkbddaaffffjja....",
  "...aiffffjaffffffffffjbdhffffffiia....",
  "...afffffjhffffffffffjkdaffffffifja...",
  "...afffffjjaffffffffjjahaffffffijja...",
  "....afffjjjjaaaaaaaaaakbafffffffjja...",
  "....ahffjjabbkdibiiihdbdhfffffffjja...",
  "...afhkhjjkkbbbbllmbbbbkkaffffkhhha...",
  "..afffkhhhkkbbbllllmbbbkkhhhhhhhfjja..",
  "..affffjhhkkbbmlllllbbbkkhhhhhfffjja..",
  ".aiiiifjjjhbbbmllllmbbbbhhhafffffjjja.",
  ".aiiiiijjjahhbbmllmmbbhhhhaafffffjjja.",
  ".aiiiiijjaaakbbbmmmbbbkkkaaaiiiiiiiia.",
  "aafffjiijaaabbkibbbdkbihaaaaiiiiiiiija",
  "affffffjjaaaahkkbbdkkhaajjaaiiiiiiiija",
  "alffffjjjaffjaakkkkkkaaffjjaffffffjjja",
  "amffffjjaffffjhakkkkhaffffafffffffjjja",
  "affhkkhkaiiiijjkaaaaaafiiiaffffffjlmma",
  "affhkkhafiiiiiiia....afiiiaffffffjmmma",
  ".ajkkahaiiiiiiija....aiiiiakkhfffjjmja",
  "..akkhhafffffjjja....afjjjjakakffjjjja",
  "..aaaaafffffjjjjja..ajfffffjakkkhjjja.",
  "......afffffjjjjja..afffffffjakhhhjaa.",
  "......aaaaaaaaaaaa..aaaaaaaaaaaaaaaa.."
], {"hd": false, "raw": true, "anim": {"kind": "heavy", "foot": 33, "head": 21, "arm": [18, 33, 9]}});
