'use strict';
// 자동 생성: 도구/에셋변환/PNG넣기.py — 손으로 다듬은 PNG를 그대로 옮긴 것. 고칠 때는 PNG를 고치고 다시 만든다.
// hd: 도트 1칸 = 화면 1px, raw: 자동 도트 규칙을 적용하지 않음 (사람이 다듬은 픽셀 그대로)
M('jelly', '등불 해파리', 'ranged', {"a": "#110d0a", "b": "#d4f4f2", "d": "#68c9c4", "f": "#70482a", "g": "#feed9e", "h": "#fefcf2", "i": "#795033", "j": "#29847c", "k": "#62a92f", "l": "#90ddda", "m": "#477022"}, [
  "....aaaa.....",
  "...abbbba....",
  "..abdaadba...",
  ".abddaaddba..",
  "abddaffaddba.",
  "abddaghaddba.",
  "abddaggaddba.",
  ".abdaifadba..",
  "..abbbbbba...",
  "..aaajjaaaa..",
  ".akkallaakka.",
  "akkmabbaakka.",
  "akkaabbbaakka",
  ".aka.abbaaka.",
  ".aka.abaa.a..",
  "..a..aba.....",
  "......a......"
], {"hd": false, "raw": true, "foot": 1, "fly": 10, "anim": {"kind": "hop"}});
M('frogKnight', '개구리 기사', 'swarm', {"a": "#120d0a", "b": "#fafaf9", "d": "#978f89", "f": "#d5cdc5", "g": "#827c77", "h": "#7c4e2d", "i": "#fcda50", "j": "#60a430", "k": "#fde4b1", "l": "#beb4ac", "m": "#53992e", "n": "#c4bdb7", "p": "#b1a8a1", "q": "#e9dda1", "r": "#82593a", "s": "#e3ddd7", "t": "#8c857f"}, [
  "..aa............",
  ".aaaa...........",
  "abddba..........",
  "afggfa..........",
  "affffa..........",
  ".aadaaa.aa......",
  "..ahaiiaiia.....",
  "..ahaaijaiaa....",
  "..ahajjjjjjaaa..",
  "..aaakkkkkallla.",
  "..akaajmmannhlpa",
  "..akaqkkkanrshla",
  "..ahaqkkkallrlta",
  "..ahajakkqadtta.",
  "...akkaaaakaaa..",
  "....aa....aa...."
], {"hd": false, "raw": true, "anim": {"kind": "hop", "top": 4}});
M('crab', '집게게', 'tank', {"a": "#110c09", "b": "#f5954d", "d": "#e75430", "f": "#64ab32", "g": "#fcda50", "h": "#efcf4b", "i": "#fbe6ba", "j": "#f7e68a", "k": "#e2cca9", "l": "#24776f", "m": "#2d8981", "n": "#3a7e31"}, [
  ".....aaaa.................",
  "...aabdbba................",
  "..abbdddda................",
  ".abddbdda.................",
  ".abdddda..........aa......",
  "abdbdda.a........affa.....",
  "adddddaada..a.a..affaaa...",
  "adddddddda.agaha.aafaiia..",
  "addddddda..ajaja.afaikkia.",
  ".addddda...aaaaaaffaikiia.",
  ".addddaa.aalllllaffaikkia.",
  "..addddaaalmmmmlafffaiiafa",
  "...aadidalmmmmmllafffaanfa",
  ".....aaaaaiiiiiikaaafaaaaa",
  ".....adaadaiiiikadddaabdaa",
  "....abdadbdakkkadbddaaddda",
  "....adaadda.aaaddddda.adda",
  "....adaada.....aadda...ada",
  ".....aa.a........aa.....a."
], {"hd": false, "raw": true, "anim": {"kind": "scuttle", "foot": 13, "band": 4}});
M('lampGhost', '익사한 등불 유령', 'ranged', {"a": "#100c09", "b": "#64a830", "d": "#d5f4f2", "f": "#93dcd9", "g": "#5c8f2b", "h": "#fcca34", "i": "#7d5032", "j": "#f9a222", "k": "#c6ebe8", "l": "#fdd747", "m": "#fefeff", "n": "#80cfc9", "p": "#fcbd22", "q": "#a3e3e1", "r": "#4f8029"}, [
  "...........aa...........",
  "..........abbaa.........",
  ".........aaabbbaa.......",
  "........addfaabbba......",
  ".......addddfagbba......",
  "......adddddfagbbga.....",
  "......adaddadfabbbba....",
  "......adhddhdfabbbba....",
  "..aaa.adaddadfaagbba....",
  ".aiiiadddddddfababbga...",
  ".aaiaadddddddfabagbba...",
  "..aiaafdbddddfabbagba...",
  "..aia.afbddddfabbagba...",
  "..aia..abfdddfabbaaga...",
  ".aiiia.abbfdddfagafa....",
  ".aiiia.abbaddddagaffdd..",
  "ajhhja.abbafdddfaddfddk.",
  "almmla.abbbaddddaddknddd",
  "alppla..abbaqdndfddd.ndd",
  ".aiia...abbandnddddd..nn",
  ".aiia...agbanddnnddd....",
  "..aa....agbbaddd.ndd....",
  ".........agbaddd.nddk...",
  ".........agbannd..nnd...",
  ".........aagba.n....nn..",
  "..........arga..........",
  "...........aa..........."
], {"hd": false, "raw": true, "fly": 10, "anim": {"kind": "flap", "wingBox": [0, 5, 5, 26]}});
M('bellOctopus', '종을 쓴 대왕문어', 'boss', {"a": "#110c09", "b": "#b67b2d", "d": "#fcd95a", "f": "#e4a334", "g": "#52922b", "h": "#62a830", "i": "#d19633", "j": "#4f7e2a", "k": "#e65431", "l": "#b23b29", "m": "#fde4b3", "n": "#3c7b26", "p": "#66451d", "q": "#fbb420", "r": "#fde874", "s": "#505624", "t": "#a4371c"}, [
  "................aaaaa..................",
  "................abbba..................",
  "...............addfffa.................",
  "...............adaaffa.................",
  "...............adbbffa.................",
  "............aaaaafffaaaa...............",
  "...........aghaddffffahha..............",
  "...........ahabbbbbbbiahha.............",
  "..........ahhaddffffffahhha............",
  "..........ahhaddffafffajhha............",
  "...........ahadffaaafffahha............",
  "...........ahadfaaaafffaaa.............",
  "...........aaadfaaaafffa.........aaa...",
  "...........abddffbbbfffa........akkka..",
  "...aaaa....abddffffffagha......akkkkla.",
  "..akkkka..abbbbbbbbbbahhha....akkkklla.",
  ".akllkkka.abddffffffffaahha...akklaaa..",
  ".alaakkkaabbddaaaaaaaffagha...akkmla...",
  "..a.amkkaabbaaaaaaaaaaaanhha..akkmma...",
  "....amkkaapaaaqaaaaaqaaaahha...akkkla..",
  "....akkkaaaaaarakkkaralaaaha...akkkla..",
  "...ammkklaaakaaakkkaaakkaahha.akkkmmaa.",
  "...ammkkllaakkagkkkkkkkkaaghaakkkkkmala",
  ".aakkkkaaaakkkahkkkkkkkkkaaallaakmmlala",
  ".alkkklahhakksahakkkkkkkkkakkahhammalla",
  "alkkklahhhakksahakmmkkkkkktakkahhaalll.",
  "alkklahhhakkksahhammkkkkkkkakkkahlalla.",
  "alkkaahhhammklaahaakkmmkkkkkammahlaaa..",
  ".akllahhaammkklaha.akmmkkkkkammkgkla...",
  "..aaaahha.ammklaha..aaakmmkkaamkakkla..",
  "......aha.ammklaa.....akmmkaaaakkkkkla.",
  ".......aa.allllla....allllaa..aallllla.",
  "...........aaaaa......aaaa......aaaaa.."
], {"hd": false, "raw": true, "anim": {"kind": "scuttle", "foot": 22, "band": 6, "fps": 6}});
