'use strict';
// 자동 생성: 도구/에셋변환/PNG넣기.py — 손으로 다듬은 PNG를 그대로 옮긴 것. 고칠 때는 PNG를 고치고 다시 만든다.
// hd: 도트 1칸 = 화면 1px, raw: 자동 도트 규칙을 적용하지 않음 (사람이 다듬은 픽셀 그대로)
M('goblin', '고블린 약탈꾼', 'swarm', {"a": "#291916", "b": "#a2ad49", "d": "#8d5837", "f": "#804e32", "g": "#fcebd1", "h": "#59572d", "i": "#65402b", "j": "#806f38", "k": "#a47956", "l": "#706c32"}, [
  ".......aaaa........",
  "......abbbba.aaaa..",
  "....aabbbbbbadddfa.",
  "...ababbbbbbaaaddda",
  "...abbbbbbbbbbbadda",
  "....ababbabbbbaddda",
  ".a..ababbabbaadddda",
  "aga..abbbbbhaddddda",
  "agga..aaaafbaidddia",
  ".aggaaaafjdbbaadfa.",
  "..akabbadfjbbaaaa..",
  "...aabaaaffdla.....",
  ".....a.aadaaaa.....",
  ".......aaaaaaaa....",
  "......aaa....aa...."
], {"hd": false, "raw": true, "anim": {"kind": "walk"}});
M('warBoar', '전투 멧돼지', 'charger', {"a": "#271815", "b": "#905d3e", "d": "#fec651", "f": "#e6a640", "g": "#fed67b", "h": "#c7923a", "i": "#9d6645", "j": "#87542f", "k": "#76492b", "l": "#d09b4d", "m": "#fdebce"}, [
  "...............aa...........",
  "..............abba.aa.......",
  "........aa....abbbaddaa.....",
  "......aaaa..aabbbafgfdha....",
  "....a.aaaaaaaaabbagfgdha....",
  "....aaaaaiiiajjaaafgfhha....",
  "...aiaaaiiiiajjjjaaaaaaaa...",
  "...aiaiiiiiaaajjjjajjjjjaa..",
  "...aiiiiiiiiiajjjjakjlkkaa..",
  ".aaiiiiaiiiiiaakjjakkbkkaaa.",
  "amaiiiiaiiiiiiaakkakkkkka.aa",
  "amaajiiiiiiiiiiaaaaaaaaaa...",
  "ammakmiiiiiiiiiikaiiiiiia...",
  "ammmammiiiiiiiiikaiiiiiia...",
  ".ammammmaaaiiibkaakkaiiika..",
  "..aaaaaaaaaiiiaaaaaaaakkka..",
  "......aa..akka.....aa.aaaa..",
  ".....aaa..aaaa....aa...aaa.."
], {"hd": false, "raw": true, "anim": {"kind": "walk", "arm": false}});
M('shaman', '고블린 주술사', 'ranged', {"a": "#9ce45d", "b": "#271815", "d": "#d4473b", "f": "#d4fba8", "g": "#a99073", "h": "#fde6c3", "i": "#b3997b", "j": "#bca487", "k": "#a2ad4a", "l": "#946440", "m": "#969f45", "n": "#8c5736", "p": "#788b41", "q": "#70462f", "r": "#808335", "s": "#92705b", "t": "#f2d9ba", "u": "#653d29"}, [
  "....a...................",
  "....a...................",
  ".aaa....................",
  ".aaa................bb..",
  "aaaa..............bbddb.",
  "aafaa............bgdddb.",
  "afffabbb.........bhddbbb",
  ".affbhhhb.......bhhihhdb",
  "...bhhbhb.......bhjhhdb.",
  "...bhhhhb....bbbbbjhbb..",
  "....bhhb....bkkkkbbb....",
  ".....blb..bbkkkkkkmbbb..",
  ".....bnb.bpbkkkkkkkbkkb.",
  "......bn..bpkbkkbkkkkb..",
  "......bnb..bkbkkbkkmb...",
  ".......bq..bkkkkkkrb....",
  ".......bkb..bbbbbbbb....",
  ".......bkkbbbqhhhqqqb...",
  "........bqbbbhbhbsqqbb..",
  "........bbbbbbhhtbbkkb..",
  ".........bu.bbhqhqbkkb..",
  "..........b.bbqqbqbbb...",
  ".............bubbbub....",
  "............bbb..bbb...."
], {"hd": false, "raw": true, "anim": {"kind": "walk", "arm": false}});
M('ogre', '오우거', 'tank', {"a": "#281916", "b": "#c6b39a", "d": "#b7a58e", "f": "#9c8b76", "g": "#c79a64", "h": "#a6947e", "i": "#d1a56b", "j": "#90806d", "k": "#b18152", "l": "#895434", "m": "#857462", "n": "#643c28", "p": "#a2ad4a", "q": "#fcf1d0", "r": "#687c3e", "s": "#794a30", "t": "#84873c"}, [
  "................aaaaaaa............",
  "...............abdfffffa...........",
  "....aaa......aabbbbbbbffaa.........",
  "..aaggga....adafffffffffaha........",
  ".aggiiia....afafffffffffaja........",
  "agiiikkla....aajfffffffmaa.........",
  "aiiiklnla.....aaaaaaaaaaa..........",
  "akkkllnla.....apppppppapa..........",
  ".allllnla....appappapppppaaaaa.....",
  ".alllllla....appappappppaappppa....",
  "..alnllla....aaqppppqppaapppppp....",
  "..alnlnlla..aaaarrrrrrpslppppppa...",
  "...allalla.arrrapppppppplpppppppa..",
  "...allalla.arrrapppppppplpppppppa..",
  "....allnlaarrrrppppppppplprppppppa.",
  ".....alnnarrrrapppppppppspraappppa.",
  "......anaaarrrapppppppppapraappppta",
  "......aappparapppapppppaaaaaaappppa",
  ".....appppparappppppppahhhhhhappppa",
  ".....appppaaraaaaaaaaaahhhhhhappppa",
  "......apppaaaassslslsllabbbbaapppa.",
  ".......aaasaarssslsllllabbbfaaaaa..",
  ".........aaapppsllllllsnaaaaaa.....",
  "...........appppaaasllaaarrrra.....",
  "...........apppprraaaa..arrrrra....",
  "...........aapppaa.......arrrra....",
  "..........apppppa........arrrra....",
  "..........aaaaaa..........aaaa....."
], {"hd": false, "raw": true, "anim": {"kind": "heavy"}});
M('goblinChief', '고블린 족장', 'boss', {"a": "#271815", "b": "#f9e5c5", "d": "#9b8974", "f": "#fbc050", "g": "#69412e", "h": "#e8d3b5", "i": "#ca3e33", "j": "#a3ae4a", "k": "#c18c3a", "l": "#939b44", "m": "#dac5ac", "n": "#824f2b", "p": "#705f51", "q": "#8d5938", "r": "#d4483c", "s": "#a13930", "t": "#773429", "u": "#7f9245", "v": "#be4639", "x": "#9d6645", "y": "#708342", "z": "#883a2c", "A": "#a8733e", "B": "#907c6b", "C": "#c39875", "D": "#a54d3a", "E": "#b68764", "F": "#936a4f"}, [
  "........aa...............................",
  ".......abba...........a..................",
  "..aa...adbba.........afa.................",
  ".aba..adddbba.......aafaa................",
  "abbaaagadddba......afafafa...............",
  "abbdddggaddha......affiffa.aa............",
  "abbddddagaada...a..affiffaajja...........",
  "abbdddddaa.a...ajaaaffffkaljja...........",
  "abbmdddaana....ajjjaaaaaajjja............",
  ".abbbdp..aqa....ajjjjjjjjjjja............",
  "..abbbd...aqa....ajjajjajjja.............",
  "...aabd....aqa....ajajjajjaaaa...........",
  ".....aa.....anaa..ajjjjjjarrrsaa.........",
  "............aajjaataaaaaarrrrrrra........",
  "..........aaaajjauaassiisaairrrrraaaa....",
  "........a.aaaaaaanaaasiajjlarrrrrrrrvaa..",
  "........aaaaaaaxannnaaajjjyatzrrrrrrrrra.",
  ".......aaaaaaxxxxannnaajjaayattrrrrrrrrra",
  ".......axaagxxxggaannnaaayjyatttrrrrrrrra",
  ".......axaaxxxxggaaAnngaaajjaatttrrraaaa.",
  ".......axaxxxxxxxaaaAnggaaaaaAatttrra....",
  ".......axxxaxxxxxxaaaAggaannxAaatttra....",
  "...aa.axxxxaxxxxxxgaaAggaaxxxAaaaataa....",
  "..abBagxxxxgxxxxxxxgaagaaaggaaaxxaaa.....",
  "..abBxxxxCxxxxxxxxxxaafffaaaaDxxxa.......",
  "..abbagxEbxxxxxxxxxxxafaftzssxxxxa.......",
  "..abbBaaFbbxxxxxxxxxxaffftsssxxxxa.......",
  "...abbBaabbbgggxxxxxgaattsssaxxxxxa......",
  "....aaaaaaaaaaaxxxaaaaassssaaaqxxxa......",
  "..........aaaaaxxxaaaaaaassaaaaaxxa......",
  ".........aaa..axxa.......aaaa...aaa......",
  ".........aaa..aaa.........aa....aa......."
], {"hd": false, "raw": true, "anim": {"kind": "heavy", "arm": false}});
