'use strict';
// 자동 생성: 도구/에셋변환/PNG넣기.py — 손으로 다듬은 PNG를 그대로 옮긴 것. 고칠 때는 PNG를 고치고 다시 만든다.
// hd: 도트 1칸 = 화면 1px, raw: 자동 도트 규칙을 적용하지 않음 (사람이 다듬은 픽셀 그대로)
M('logWorm', '이끼 통나무 애벌레', 'swarm', {"a": "#2a1a12", "b": "#7a9a3a", "d": "#f4c890", "f": "#8a5a34"}, [
  ".a....a...........",
  "..a..a............",
  ".aaaaaa...........",
  "abbbbbba.....aaaa.",
  "abbbbbbaaaaaabbbba",
  "addddbbabbbbabbffa",
  "aadadffaffffaffffa",
  "aadadffadfffadfffa",
  "addddffaddffaddffa",
  ".aaaaaaaaaaaaaaaa.",
  "..a.a...a.a..a.a.."
], {"hd": false, "raw": true, "anim": {"kind": "scuttle", "foot": 10, "band": 2}});
M('sporeFly', '포자 반딧불이', 'ranged', {"a": "#2a1a12", "b": "#f6ead8", "d": "#d8c4a8", "f": "#7a9a3a", "g": "#f4c890", "h": "#8a5a34", "i": "#3ee0c8", "j": "#d8fff6"}, [
  ".....aaa.aa....",
  "....abbbabba...",
  "a...ababadba...",
  ".a..aabbabba...",
  "..aaaaaafaa....",
  ".agggahfffhaa..",
  "aggggghhfhaiia.",
  "agagaghhhhaijia",
  "aggggghhhhaijia",
  ".agggahhhhaiia.",
  "..aaaaaaaaaaa..",
  "...a.a..a.a...."
], {"hd": false, "raw": true, "fly": 10, "anim": {"kind": "flap", "wingBox": [4, 12, 0, 4], "wingAmp": 1}});
M('sawCrab', '녹슨 톱 게', 'charger', {"a": "#251810", "b": "#c66734", "d": "#b09b8b", "f": "#ae4a28", "g": "#b45b2e", "h": "#9f5d37", "i": "#837161", "j": "#796758", "k": "#5c4c3d", "l": "#a79280", "m": "#6f3c21", "n": "#645446", "p": "#93a63c", "q": "#8b8836", "r": "#7e9133", "s": "#804828", "t": "#98502c", "u": "#8f4121", "v": "#fde9c3"}, [
  "..............a......",
  "..........aa.aba.....",
  ".........addafggaa...",
  "........adddghgddda..",
  ".......adddiiiiidda..",
  ".......ajdiikkkiiiga.",
  "......addiiklalkiggga",
  ".....aagdiikamaniifa.",
  ".....apagaaklalkiiia.",
  "..aa.aqaapaakkkiiia..",
  ".abgaaaprrrraiiiia...",
  ".afffaarrrrrraihlaa..",
  "agffaaaaaaasraataufa.",
  "affaaaavavamffuafaffa",
  "afa.afaaaaaaaffaffafa",
  ".aa.afa.....afa.afaa.",
  ".a...a.....affa..a...",
  "............aa......."
], {"hd": false, "raw": true, "anim": {"kind": "scuttle", "foot": 13, "band": 4}});
M('mossBear', '이끼곰', 'tank', {"a": "#271a11", "b": "#b26739", "d": "#8b4c2b", "f": "#995630", "g": "#94a93c", "h": "#839535", "i": "#c0afa0", "j": "#753e23", "k": "#9d8b7d", "l": "#cdbcad", "m": "#6a802e", "n": "#b3a193", "p": "#5a5525", "q": "#b77b50", "r": "#5d7429", "s": "#fbd8b3", "t": "#fce2c2", "u": "#f4c395"}, [
  "................aa.............",
  "...............abda............",
  "..............adda.............",
  ".........aaaaafdaaaa...........",
  ".......aaghhaijahhhhaa.........",
  "......aghhhakklahhhhhha........",
  ".....aghhhhhakklajhhhhhaa......",
  "....aahhdhhmmanaddphhhhhhaa....",
  "..aadahaahhhhhahdddmhhhhhhha...",
  ".addddaddahhhhhhddddhhmjhhhha..",
  ".adddddaqamhhhhhhddddhpdhhhma..",
  ".adddddddddhphhhhadddhdddhrdda.",
  ".addaddddadhdhhhhajddddddhjdda.",
  "asssaddddddddhhhjdaddddddhdddda",
  "aassdddddaddddhjdddadddddddddda",
  "asssdddddaadddrddddaaddjddddda.",
  ".aaaaaaaaaaaddddddda.aaaddddda.",
  "....aaaaaaaaadddddda...addddda.",
  "...aaaaaaaaaadddddda....adddda.",
  "...ajjaaaa..addddda.....aaaaaa.",
  "..asatata..atataua.....aaaaaa.."
], {"hd": false, "raw": true, "anim": {"kind": "heavy", "top": 3, "foot": 16, "arm": false}});
M('angryTree', '분노한 고목', 'boss', {"a": "#251810", "b": "#8b4c2a", "d": "#8a9d3b", "f": "#819435", "g": "#a96433", "h": "#95642f", "i": "#7e5b2a", "j": "#733f23", "k": "#647c2d", "l": "#748530", "m": "#555123", "n": "#fde8c4", "p": "#9a8879", "q": "#84725b", "r": "#5d825e", "s": "#d4c5b7", "t": "#b3a091", "u": "#5a7129", "v": "#e8a66d", "x": "#f9d9b0", "y": "#897633"}, [
  "........a.....a...........a.........",
  ".......abaa..ada.........aba........",
  "........abbaaafa......aaabba........",
  ".....a...abbaafaaa...aabbba...a.....",
  ".a..aba...abbffffdaaafbbaa...aba....",
  "aba.aba....affffffagfbbaa...abba....",
  "abbaaffa..afffbfffhbibba...affa..a..",
  ".ajfffffaaakfbbfabbbbbbaaaaffflaaja.",
  "..afafflbbaambbmbbbbbbbababffffffaa.",
  "...a.afaabbbbbbbbbbbbbbbbbbaaalfaa..",
  ".....afaaabbbabbbbbbabbbbbaa..afa...",
  "......a..aabbaaabbaaabbbbajaa..a....",
  "..........abbanaaaanabbbbaappa......",
  "..........abbaqaaaaqabbjaapppaa.....",
  ".......r..aabaadaddaabbaspppabba....",
  ".........aaabadffffdabbbastpaabba...",
  "......aaaabaadffffffdabbbassa.aba...",
  ".....adfffbbaffffffffabbbbaa...a....",
  "....adfkfbbaafkffffufabvbbbaaa......",
  "...afbbbbbaaalaffffaabbxvbbbbfaa....",
  "...agbbbbaa.aaaffffaabbbxvabbyffa...",
  "...abbbbba....affffabbbbbbaaabbffa..",
  "..abbbjbba....akfkkajbbbbba..abifa..",
  ".abbbaabbja....akaaaaabvvxaa.abbba..",
  ".abaaabbbaa.....aa..ajbjbbba..abbba.",
  "abbaabaabbaa.......aabbaabba..ababa.",
  "aba.aba.abba......aabba..abbaabbaaba"
], {"hd": false, "raw": true, "anim": {"kind": "heavy", "top": 7, "foot": 21}});
