'use strict';
// 자동 생성: 도구/에셋변환/PNG넣기.py — 손으로 다듬은 PNG를 그대로 옮긴 것. 고칠 때는 PNG를 고치고 다시 만든다.
// hd: 도트 1칸 = 화면 1px, raw: 자동 도트 규칙을 적용하지 않음 (사람이 다듬은 픽셀 그대로)
M('iceSlime', '얼음 방울', 'swarm', {"a": "#2e1414", "b": "#fcf6ea", "d": "#e2d8c8", "f": "#e03c2c", "g": "#b02a24", "h": "#d2e8fc", "i": "#7aa2ee", "j": "#a2c4f4"}, [
  "........aaa.",
  ".......abbda",
  "......aabbda",
  "....aafffbda",
  "...afffffgga",
  "..abbbbffgga",
  "..abbbbbbbga",
  ".aaaaaaabbda",
  ".ahhhhhiaaa.",
  "ahahhahiiia.",
  "ahahhahiiiia",
  "ahhhhhhjiiia",
  ".ahhhhjjjia.",
  "..aaaaaaaa.."
], {"hd": false, "raw": true, "anim": {"kind": "hop", "top": 4, "upper": 9}});
M('crystalBeetle', '수정 딱정벌레', 'charger', {"a": "#2e1414", "b": "#eef6fc", "d": "#d2e8fc", "f": "#7aa2ee", "g": "#78503e", "h": "#5a3a30"}, [
  "..........aa.........",
  ".........aba.........",
  "aa......abda.........",
  "aba...aabbddaaaa.....",
  "adbaa.afbbffddba.....",
  "adbdfadfbfffdbda.....",
  ".addfaaaffdbdbdfaaaa.",
  ".affdfggafbddbdffba..",
  "..afffgggaddffdfdda..",
  "...afgbagafdfffddfa..",
  "..agggbaggafffffffa..",
  "..aggggghagghaaaggha.",
  "..aggaaaaggaaaggahha.",
  "..agha..agha.aghaaaha",
  "..aaa...aaa..aaa..aaa"
], {"hd": false, "raw": true, "anim": {"kind": "scuttle", "foot": 12, "band": 6}});
M('frostOwl', '서리 부엉이', 'ranged', {"a": "#2e1414", "b": "#d2e8fc", "d": "#fcf6ea", "f": "#e2d8c8", "g": "#a2c4f4", "h": "#f8a02a", "i": "#e03c2c", "j": "#b02a24"}, [
  ".aa........a.....a.",
  ".aba..aaaaaba...aba",
  ".abbaadddddba.aabba",
  "abddadddddddaaddbba",
  "abdfadaddaddgdfdbba",
  "abdfadaddaddgdffbba",
  ".abdaddhhdddgddfbba",
  ".abdaddddddiiddbba.",
  "..abaiiiiijiiddba..",
  "...aaiiiijjiigaa...",
  "....adddddfiiiaba..",
  ".....addfdfiiija...",
  ".....aadfddiiija...",
  "......aaaaaaiija...",
  "......ahaha.aaa....",
  ".......a.a........."
], {"hd": false, "raw": true, "fly": 10, "anim": {"kind": "flap", "foot": 10}});
M('frostYeti', '서리 설인', 'tank', {"a": "#2e1414", "b": "#fcf6ea", "d": "#e2d8c8", "f": "#e03c2c", "g": "#6688cb", "h": "#b02a24", "i": "#fcd070", "j": "#f0a830", "k": "#c47e2c", "l": "#4c68b0"}, [
  "..........a.............",
  "........aabaaaa.........",
  ".......abbbbbbba........",
  "......abbbbbbbdda.......",
  ".....abbbbbbbbbdda......",
  ".....abbbbbbbbbddfa.....",
  ".....abggbbggbbdffha....",
  ".....abgaggagbbdffha....",
  ".....abgaggagbbfffhaa...",
  "....afbggggggbfffhbbba..",
  "....affbbbbbfffffdbbbba.",
  "...abfffaafffffhbbbbbda.",
  "..abbffaijafffhbbbbbbda.",
  ".abbbafaijafhbbbdbbbbba.",
  ".abbbabajkabbbbbdbbbbbda",
  "abbbbabbaabbbbbdbbbbbbda",
  "abbbbabbbbbbbbbbabbbbbba",
  "agbgbabbbbbbbbbbagbgbgba",
  "aggggabbddddddbbagggggga",
  ".agglabbbbaaaabbbagggla.",
  "..aaabgbgba..abgbgaaaa..",
  "....aggglga..agggglga...",
  "....aaaaaaa..aaaaaaaa..."
], {"hd": false, "raw": true, "anim": {"kind": "heavy", "head": 10, "foot": 20, "arm": [11, 20, 5]}});
M('iglooMimic', '이글루 흉내쟁이', 'tank', {"a": "#2e1414", "b": "#fcf6ea", "d": "#d2e8fc", "f": "#7a1c1a", "g": "#f0a830", "h": "#c47e2c", "i": "#fcd070", "j": "#2a2844", "k": "#a2c4f4"}, [
  "..........aaaaa.........",
  "........aaabbbaaa.......",
  ".......addddddddda......",
  "......adbbbbdbbbddaa....",
  "....aafbbbbbdbbbffgga...",
  "...afffffbbbbffffdgha...",
  "..agigbbfffffbbbgiddda..",
  "..agigbgigbbgibbghdbda..",
  "..abhbbgghbbghbbbbdbdda.",
  "..adbbbbhbbbbbdbbbbbdda.",
  ".addddjbbjjbbjbbdbdddda.",
  ".abbbjjbjjjbjjjbdbbddda.",
  ".abdbjjjjjjjjjjbdbbddda.",
  ".adddjjjjjjjjjjbkkkkdda.",
  "abbbdjjbjjjbjjjkbbbkddda",
  "abbbdjbbbjjbbbjkbbbkddda",
  "aaaaaaaaaaaaaaaaaaaaaaaa"
], {"hd": false, "raw": true, "anim": {"kind": "mimic", "upper": 10}});
M('snowKing', '모자 쓴 눈사람 왕', 'boss', {"a": "#2e1414", "b": "#fcd070", "d": "#f0a830", "f": "#e03c2c", "g": "#fcf6ea", "h": "#b02a24", "i": "#d2e8fc", "j": "#a2c4f4", "k": "#7aa2ee", "l": "#9c6844", "m": "#e2d8c8", "n": "#6e4a36", "p": "#f5701a", "q": "#c47e2c"}, [
  "...................aa...........",
  "..................abda..........",
  ".................abbbda.........",
  "..................abda..........",
  "..............aaaaabdaa.........",
  ".............afffggfffhaa.......",
  "....a.......affbdffffffhha......",
  "...aga......affbdfffffffhha.....",
  "..aigia....abfbbbdfffbdfhha.....",
  ".aiigiia...abffbdfffbbbdhha.....",
  ".aigjiia...adffbdffffbdfhha.....",
  "agijkjgia.aggggggggffbdhdha.....",
  "aiijkjjia.agggggggggggghda......",
  ".alikjla..ammmmmmmggggaaaa......",
  "..alkla....agagggammmmggga.aa...",
  ".aaakla...aagagggaggiimggaagga..",
  "aggalna..apppppggaggiiiggaaggia.",
  "agillnaa..appppgggggiiiga.agiia.",
  "aiialngia.aaaaaggggggifffaaiia..",
  ".aaalniiaaffaaaaaaafffffha.alaa.",
  "...alnaa.afgbbdfffffffffhaallgia",
  "...alnaaabdfbdqffffffhggmllaaiia",
  "...agggiadqadaqhhhbddggllaa..aa.",
  "..agggiiaqqaaaaaaabddaffffha....",
  "..agiiiiagggggggggdaqagffffha...",
  "...aiiiaagggggggggaaaaggfffha...",
  "....alnaagggaaggggggiaggffffha..",
  "....alnaagggaaggggggiaggffffha..",
  "....alnaagggggggggggiagggfffha..",
  "....alnaagggaagggggiiiagggfffha.",
  ".....alnagggaagggggiiiaggggffha.",
  ".....alnaigggggggggiijjagggfffha",
  ".....alnaiiiiiiiiiijjjjaggggggga",
  ".....alnaaiiiiiiiiijjjjaagggggga",
  "......aa..aaaaaaaaaaaaa..aaaaaa."
], {"hd": false, "raw": true, "anim": {"kind": "hop", "top": 5, "upper": 24, "fps": 4}});
