// 이펙트 에디터에서 저장한 이펙트 (에셋/이펙트/*.json 에서 만든다. 손으로 고치지 않는다)
const PIXFX_LIST = [
  {"name": "기본 마법진", "slot": "공용 마법진", "seed": 1, "frames": 24, "size": 48, "fps": 12, "loop": true, "anchor": "center", "move": "orbit", "emitter": "ring", "emitR": 0.15, "chaos": 0.2, "count": 72, "spawn": 0.2, "psize": 1, "sizeLife": "same", "shapes": ["dot", "dot", "plus"], "speed": 1, "gravity": 0, "spin": 0.5, "fade": "none", "fadeStr": 1, "palette": "은하", "colors": null, "shades": true, "range": 0.6, "colorLife": false, "outline": false, "glow": true, "dir": null, "spread": 360, "squash": 1, "driftX": 0, "driftY": 0, "rings": 3, "sRx": 20, "sRy": 6, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 5, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "기본 방사선", "slot": "공용 방사선", "seed": 1, "frames": 10, "size": 48, "fps": 20, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0.5, "count": 14, "spawn": 0, "psize": 3, "sizeLife": "same", "shapes": ["streak"], "speed": 1, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 1, "palette": "빛", "colors": null, "shades": true, "range": 0.6, "colorLife": false, "outline": false, "glow": true, "dir": null, "spread": 360, "squash": 1, "driftX": 0, "driftY": 0, "rings": 1, "sRx": 20, "sRy": 6, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 5, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "기본 불똥", "slot": "공용 불똥", "seed": 1, "frames": 10, "size": 40, "fps": 20, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0.6, "count": 14, "spawn": 0, "psize": 2, "sizeLife": "same", "shapes": ["streak"], "speed": 1, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 1, "palette": "불꽃", "colors": null, "shades": true, "range": 0.3, "colorLife": true, "outline": false, "glow": true, "dir": null, "spread": 360, "squash": 1, "driftX": 0, "driftY": 0, "rings": 1, "sRx": 20, "sRy": 6, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 5, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "기본 섬광", "slot": "공용 섬광", "seed": 1, "frames": 8, "size": 24, "fps": 20, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0, "count": 1, "spawn": 0, "psize": 6, "sizeLife": "shrink", "shapes": ["star"], "speed": 0, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 0.5, "palette": "빛", "colors": null, "shades": false, "range": 0.5, "colorLife": true, "outline": false, "glow": true, "dir": null, "spread": 360, "squash": 1, "driftX": 0, "driftY": 0, "rings": 1, "sRx": 20, "sRy": 6, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 5, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "기본 연기", "slot": "공용 연기", "seed": 1, "frames": 12, "size": 32, "fps": 16, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0.6, "count": 8, "spawn": 0, "psize": 4, "sizeLife": "grow", "shapes": ["circle"], "speed": 0.8, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 1, "palette": "연기", "colors": null, "shades": true, "range": 0.5, "colorLife": false, "outline": false, "glow": false, "dir": null, "spread": 360, "squash": 0.6, "driftX": 0, "driftY": -4, "rings": 1, "sRx": 20, "sRy": 6, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 5, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "기본 칼자국", "slot": "공용 칼자국", "seed": 1, "frames": 10, "size": 64, "fps": 24, "loop": false, "anchor": "center", "move": "slash", "emitter": "point", "emitR": 0.15, "chaos": 0, "count": 160, "spawn": 0, "psize": 2, "sizeLife": "same", "shapes": ["dot"], "speed": 1, "gravity": 0, "spin": 1, "fade": "none", "fadeStr": 1, "palette": "빛", "colors": null, "shades": true, "range": 0.25, "colorLife": true, "outline": false, "glow": false, "dir": null, "spread": 360, "squash": 1, "driftX": 0, "driftY": 0, "rings": 1, "sRx": 26, "sRy": 8, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 6, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "기본 파편", "slot": "공용 파편", "seed": 1, "frames": 12, "size": 40, "fps": 20, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0.6, "count": 10, "spawn": 0, "psize": 2, "sizeLife": "same", "shapes": ["diamond", "dot"], "speed": 1, "gravity": 0.6, "spin": 1, "fade": "out", "fadeStr": 1, "palette": "빛", "colors": null, "shades": true, "range": 0.4, "colorLife": true, "outline": true, "glow": false, "dir": null, "spread": 360, "squash": 1, "driftX": 0, "driftY": 0, "rings": 1, "sRx": 20, "sRy": 6, "sRot": 0, "sA0": -80, "sA1": 75, "sW": 5, "sGrow": 0.25, "reach": 0, "alpha": 1, "at": -1},
  {"name": "레벨업 빛기둥", "slot": "레벨업", "seed": 1, "frames": 20, "size": 64, "fps": 16, "loop": false, "anchor": "bottom", "move": "rise", "emitter": "line", "emitR": 0.3, "chaos": 0.3, "count": 40, "spawn": 0.45, "psize": 2, "sizeLife": "same", "shapes": ["star", "dot", "plus"], "speed": 1.2, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 0.9, "palette": "빛", "colors": null, "shades": true, "range": 0.4, "colorLife": true, "outline": false, "glow": true},
  {"name": "처치 연기", "slot": "처치", "seed": 1, "frames": 14, "size": 40, "fps": 16, "loop": false, "anchor": "bottom", "move": "burst", "emitter": "line", "emitR": 0.4, "chaos": 0.5, "count": 12, "spawn": 0.15, "psize": 5, "sizeLife": "shrink", "shapes": ["circle"], "speed": 0.45, "gravity": -0.5, "spin": 1, "fade": "out", "fadeStr": 0.8, "palette": "연기", "colors": null, "shades": true, "range": 0.4, "colorLife": true, "outline": true, "glow": false},
  {"name": "치명타 별", "slot": "치명타", "seed": 1, "frames": 12, "size": 40, "fps": 20, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0.4, "count": 10, "spawn": 0, "psize": 3, "sizeLife": "shrink", "shapes": ["star"], "speed": 1, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 1, "palette": "빛", "colors": null, "shades": true, "range": 0.5, "colorLife": true, "outline": false, "glow": true},
  {"name": "타격 불꽃", "slot": "타격", "seed": 1, "frames": 8, "size": 32, "fps": 20, "loop": false, "anchor": "center", "move": "burst", "emitter": "point", "emitR": 0.15, "chaos": 0.45, "count": 16, "spawn": 0, "psize": 3, "sizeLife": "shrink", "shapes": ["circle", "plus"], "speed": 0.55, "gravity": 0, "spin": 1, "fade": "out", "fadeStr": 0.6, "palette": "불꽃", "colors": null, "shades": true, "range": 0.3, "colorLife": true, "outline": false, "glow": true},
];
